### ISSUE TITLE
Choose a SCID base encoding and use it directly

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/trustdidweb#115] opened 2024-10-02 20:23 UTC
We recently had a lot of discussions to decide on what the encoding for the SCID is... and I'm not happy with what we landed on.

Here is an example of a DID as the spec is right now: `did:tdw:QmfGEUAcMpzo25kF2Rhn8L5FAXysfGnkzjwdKoNPi615XQ:domain.example` and here is another `did:tdw:QmQdKxfNSLUUFeGraghwvvBKJ9Qc4Ta1RYbitQSmr639Wd:localhost%3A8000`

When glancing at the 2 of them (or imagine if there was even more..) as a human it takes quite a bit to determine they are different. The `Qm` is repeated and it will be repeated for all DIDs. I don't think we gain anything from having multibase encoding here and propose we should drop it in favour of specifying in the spec that we are using base58btc encoding with a link to this expired IETF draft https://datatracker.ietf.org/doc/html/draft-msporny-base58-02

Also... identifiers beginning with `Q` has already been co-opted by something we don't want any association with...

**Comment by swcurran** [comment] 2024-10-02 21:02
Agreed — good point!

Should I rush this into 0.4, or this will part of 0.5?  0.4 just get merged — safe enough to do another very quick update?

**Comment by brianorwhatever** [comment] 2024-10-02 21:58
I am good either way. Would love to implement this with 0.4 but we should first form consensus around it

**Comment by andrewwhitehead** [comment] 2024-10-02 22:04
I'd also prefer not having a common prefix on each SCID.

**Comment by swcurran** [comment] 2024-10-02 22:19
Let’s rush it into 0.4 and I’ll make an announcement about it.  I think it is a no-brainer.

**Comment by swcurran** [comment] 2024-10-02 22:29
Wait — the spec says to use multihash (necessary, I think) but not multibase.  Is the `Qm` coming from multihash, and if so, I think that is necessary and correct. 

What am I missing?

**Comment by swcurran** [comment] 2024-10-02 22:33
Confirmed that the `Qm` comes from the multihash, so no change to the spec. We aren’t using multi-base, and because the hash algorithm is more likely to change the base encoding, there is no change to make.

Phewww…

**Closed** 2024-10-04 18:39 UTC
